version: "0.2"
words:
  - addch
  - addstr
  - ARCHS
  - armv
  - attroff
  - attron
  - autoattribute
  - autoclass
  - automethod
  - calcsize
  - cbreak
  - cibuildwheels
  - CIBW
  - classmethod
  - crclength
  - currentmodule
  - datarate
  - datasheet
  - deinit
  - docstr
  - Doherty
  - Doxyfile
  - EDDYSTONE
  - endfunction
  - endl
  - endwin
  - getmaxyx
  - gpiochip
  - gpiod
  - graphviz
  - hexlified
  - HLINE
  - KBPS
  - manylinux
  - MBPS
  - millis
  - MOSI
  - MRAA
  - multicasted
  - multiceiver
  - musllinux
  - mypy
  - nocbreak
  - noecho
  - NOMASTER
  - pigpio
  - Pinout
  - pipx
  - pybind
  - pypa
  - pypi
  - pyproject
  - pypy
  - pyrf
  - repr
  - sdist
  - seealso
  - setuptools
  - SPIDEV
  - sprintf
  - STREQUAL
  - urandom
