version: "0.2"
words:
  - addch
  - addstr
  - attroff
  - attron
  - autoattribute
  - autoclass
  - automethod
  - calcsize
  - cbreak
  - classmethod
  - crclength
  - currentmodule
  - datarate
  - datasheet
  - deinit
  - docstr
  - Doherty
  - Doxyfile
  - EDDYSTONE
  - endl
  - endwin
  - getmaxyx
  - gpiochip
  - gpiod
  - HLINE
  - KBPS
  - MBPS
  - millis
  - MRAA
  - multicasted
  - multiceiver
  - nocbreak
  - noecho
  - pigpio
  - pybind
  - pyproject
  - pyrf
  - repr
  - seealso
  - setuptools
  - SPIDEV
  - sprintf
  - STREQUAL
  - urandom
